---
# 2-Spine / 6-Leaf Cumulus Linux BGP EVPN VXLAN fabric
# leaf05 and leaf06 are the external / border leafs (VRF route-leaking to the WAN/MPLS edge)

all:
  children:
    spine:
      hosts:
        spine1:
          ansible_host: 192.168.122.32
        spine2:
          ansible_host: 192.168.122.33

    leaf:
      hosts:
        leaf01:
          ansible_host: 192.168.122.34
        leaf02:
          ansible_host: 192.168.122.35
        leaf03:
          ansible_host: 192.168.122.36
#        leaf04:
#          ansible_host: 192.168.122.37
        leaf05:
          ansible_host: 192.168.122.38
        leaf06:
          ansible_host: 192.168.122.39

    border_leaf:
      hosts:
        leaf05:
        leaf06:

    fabric:
      children:
        spine:
        leaf:
