---
# 2-Spine / 6-Leaf Cumulus Linux BGP EVPN VXLAN fabric
# cl-lf-5 and cl-lf-6 are the external / border leafs (VRF route-leaking to the WAN/MPLS edge)

all:
  children:
    spine:
      hosts:
        cl-sp-1:
          ansible_host: 192.168.122.32
        cl-sp-2:
          ansible_host: 192.168.122.33

    leaf:
      hosts:
        cl-lf-1:
          ansible_host: 192.168.122.34
        cl-lf-2:
          ansible_host: 192.168.122.35
        cl-lf-3:
          ansible_host: 192.168.122.36
#        cl-lf-4:
#          ansible_host: 192.168.122.37
        cl-lf-5:
          ansible_host: 192.168.122.38
        cl-lf-6:
          ansible_host: 192.168.122.39

    border_leaf:
      hosts:
        cl-lf-5:
        cl-lf-6:

    fabric:
      children:
        spine:
        leaf:
